#ifndef _DRAWABLETYPE_HPP
#define _DRAWABLETYPE_HPP

#include <cstddef>

enum Drawable_Type {
	TYPE_INVISIBLE = 0,
	TYPE_ORGAN_LUNG,
	TYPE_ORGAN_LIVER,
	TYPE_ORGAN_HEART,
	TYPE_DEAD_ORGAN,
	TYPE_PLAYER_DEAD,
	TYPE_PLAYER_FIGHTER = 7,
	TYPE_PLAYER_HEALER = 8,
	TYPE_PLAYER_BUILDER = 9,
	TYPE_BULLET = 20,
	TYPE_MINE = 21,
	TYPE_SHOTGUN_BULLET = 22,
	TYPE_GRENADE = 23,
	TYPE_SHRAPNEL = 24,
	TYPE_EGG = 25,
	TYPE_HEALING_BULLET = 26,
	TYPE_BLACK_BULLET = 27,
	TYPE_GREEN_BULLET = 28,
	TYPE_PURPLE_BULLET = 29,
	TYPE_LAVA_BALL = 30,
	TYPE_TOWER_HURT = 45,
	TYPE_TOWER_HEAL = 46,
	TYPE_TOWER_SLOW = 47,
	TYPE_TOWER_POISON = 48,
	TYPE_TOWER_SAND = 49,
	TYPE_GREEN_MONSTER = 50,
	TYPE_BLUE_MONSTER = 51,
	TYPE_UGLY_MONSTER = 52,
	TYPE_HUGE_MONSTER = 53,
	TYPE_RED_MONSTER = 54,
	TYPE_EXPLOSION = 100,
	TYPE_HEALING_EXPLOSION = 101
};

#endif
